### ISSUE TITLE
NOT WORKING ON UBUNTU 0.12.34.534

### ISSUE THREAD

**Issue by SBoudrias** [stephenplusplus/passy#2]
plz help

npm http 200 https://registry.npmjs.org/passy/0.1.0
npm ERR! Error: package lacks shasum
npm ERR! at fetchit (/usr/local/lib/node_modules/npm/lib/cache.js:742:19)
npm ERR! at next (/usr/local/lib/node_modules/npm/lib/cache.js:712:14)
npm ERR! at /usr/local/lib/node_modules/npm/lib/cache.js:699:5
npm ERR! at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR! at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR! http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR! npm-@googlegroups.com

npm ERR! System Linux 2.6.32-5-686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "passy"
npm ERR! cwd /home/simon
npm ERR! node -v v0.8.20
npm ERR! npm -v 1.2.11

**Comment by stephenplusplus** [comment]
```
npm ERR! If you need help, you may report this log at:
npm ERR! http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR! npm-@googlegroups.com
```

**Comment by stephenplusplus** [comment]
:tongue:

**Comment by passy** [comment]
I'm most certainly working on Ubuntu!

**Comment by sindresorhus** [comment]
I tested and passy seems to only work on Windows ME.

**Comment by stephenplusplus** [comment]
> Windows ME

@passy can be so selfish sometimes!

**Comment by addyosmani** [comment]
I can't get passy working on anything but MSDOS atm.

**Comment by passy** [comment]
![](http://38.media.tumblr.com/6f010ba4d24477497afb0083a85f676b/tumblr_n1kvjiiXSP1roeqdqo1_400.gif)
