### ISSUE TITLE
gif collection, that I'm not ready to use yet, but intend to in the future

### ISSUE THREAD

**Issue by stephenplusplus** [stephenplusplus/passy#3]
![](http://s3-ec.buzzfed.com/static/2014-07/25/13/enhanced/webdr05/enhanced-25133-1406308440-13.jpg)

// @passy @sindresorhus

**Comment by sindresorhus** [comment]
This is my favorite. Universally usable.

![gxblrfn](https://cloud.githubusercontent.com/assets/170270/4063602/5eb5b302-2e09-11e4-989f-dd803dfbb35b.gif)

**Comment by stephenplusplus** [comment]
That does apply to nearly every situation.

**Comment by passy** [comment]
Wow, it's like someone put my life into a GIF.

**Comment by passy** [comment]
Does this mean the collection is complete? Are these ALL THE GIFS?

**Comment by stephenplusplus** [comment]
Never.

**Comment by passy** [comment]
![](https://media.giphy.com/media/NWoJQ8peVE78A/giphy.gif)

**Comment by stephenplusplus** [comment]
Yep, these are all of 'em :)

**Comment by passy** [comment]
:')
